name: Build PRs for LoopBack.io site

on:
  pull_request:
    branches:
      - gh-pages
  workflow_dispatch:
    branches:
      - gh-pages
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Use Node.js 22
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24.14.0

      - name: Set up Ruby 3.2
        uses: ruby/setup-ruby@c984c1a20bb35a1cbda04477c816cea024418be9 # v1.294.0
        with:
          ruby-version: 3.4.9

      - name: Install and Build 🔧
        run: |
          bundle install
          npm install
          npm ls @loopback/docs 2>/dev/null || true
          npm run build
