# Inspired by: https://github.com/actions/starter-workflows/blob/1035244887e26fbbd4f1017d919fb5995cc521c4/pages/jekyll.yml
name: Build LoopBack.io website

on:
  pull_request:
    branches:
      - gh-pages

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          disable-sudo-and-containers: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            index.rubygems.org:443
            raw.githubusercontent.com:443
            registry.npmjs.org:443
            rubygems.org:443

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24.18.0

      - name: Set up Ruby
        uses: ruby/setup-ruby@6e5d382445ae5590b7449d8b3bc8cb1c2c27f617 # v1.317.0
        with:
          bundler-cache: true

      - name: Install and Build
        run: |
          npm ci --ignore-scripts
          npm run postinstall
          npm ls @loopback/docs 2>/dev/null || true
          npm run build
