name: Build and Deploy LoopBack.io site

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Use Node.js 22
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 24.12.0

      - name: Set up Ruby 3.2
        uses: ruby/setup-ruby@d697be2f83c6234b20877c3b5eac7a7f342f0d0c # v1.269.0
        with:
          ruby-version: 3.2

      - name: Install and Build 🔧
        run: |
          bundle install
          npm install
          npm ls @loopback/docs 2>/dev/null || true
          npm run build
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@9d877eea73427180ae43cf98e8914934fe157a1a # v4.7.6
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          branch: gh-pages
          folder: .
